<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="2.28.0" />
    <PackageReference Include="Serilog" Version="4.0.0" />
    <PackageReference Include="Serilog.Sinks.MongoDB" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.0" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Portal.Core\Portal.Core.csproj" />
    <ProjectReference Include="..\Portal.Domain\Portal.Domain.csproj" />
  </ItemGroup>
</Project>
